_meta:
  type: "tenancyconfig"
  config_version: 2

# Define tenancy_config mapping name and corresponding values
# cluster1:
#   nodes_dn:
#       - CN=*.example.com

tenancy_config:
  multitenancy_enabled: true
  private_tenant_enabled: true
  default_tenant = ""
  preferred_tenant_list = {"Global", "Private"}